// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiTDYPBXpQ0zycHRPXVrW0ephJ1x6waEo',
    appId: '1:1085700955220:web:62579a6222a7293f3061c1',
    messagingSenderId: '1085700955220',
    projectId: 'novo-projeto-fb8bc',
    authDomain: 'novo-projeto-fb8bc.firebaseapp.com',
    storageBucket: 'novo-projeto-fb8bc.appspot.com',
    measurementId: 'G-4QVK9Y6S9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9byTTZyEWQ9pFSrP__pH-Pn0wlPDblTM',
    appId: '1:1085700955220:android:bd556b36e504598e3061c1',
    messagingSenderId: '1085700955220',
    projectId: 'novo-projeto-fb8bc',
    storageBucket: 'novo-projeto-fb8bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzKJsL53LiD6KhEw7quTSS_aikT81i3kg',
    appId: '1:1085700955220:ios:074960ff7d1ec4d03061c1',
    messagingSenderId: '1085700955220',
    projectId: 'novo-projeto-fb8bc',
    storageBucket: 'novo-projeto-fb8bc.appspot.com',
    iosClientId: '1085700955220-5hr24t7j4dpkrqjgep1iui9647cnod06.apps.googleusercontent.com',
    iosBundleId: 'com.example.appAh',
  );
}
